### ISSUE TITLE
Fails to generate with Ocarina of Time, filler items error?

### ISSUE THREAD

**Issue by ironminer888** [silasary/linklink#1]
Hi,

I just created my own branch of your APWorld that adds Pokemon items into the LinkLink pool. I was doing some testing to make sure my changes worked, but when I tried to include an Ocarina of Time world in the pool, the generation wouldn't complete, giving me this error: 

```AttributeError: 'NoneType' object has no attribute 'choices'
Exception in <bound method ManualWorld.create_items of <worlds.manual_linklink_silasary.ManualWorld object at 0x00000262E59508D0>> for player 2, named LinkLink.
```

I'm not sure if this is an error on the OoT world generation code or your APWorld's code, but I thought I would let you know about this bug just to be safe. [You can access my fork here](https://github.com/tstephenson888/linklink). I was also testing this with A Link to the Past, and it worked, but it had a *lot* of unplaced filler items. I'm not sure if this is intended behavior or not.

You can access the [generation logs for both the Pokemon and OoT bugs I described here](https://gist.github.com/tstephenson888/3a1a70454e12baff263579e0af891ac8) if you think they would help.

Many thanks 👍🏻

**Comment by silasary** [comment]
It's technically a bug in OOT, but I should be better at handling it
